services:
  - type: web
    name: shadowcoder-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
