/**
 * ShadowCoder Gamified RPG Achievement & Badges Catalog
 */

export const BADGE_CATEGORIES = [
  { id: 'all', label: 'All Achievements', icon: '🏆' },
  { id: 'simulations', label: 'Job Simulations', icon: '🚀' },
  { id: 'mastery', label: 'Stack Mastery', icon: '💻' },
  { id: 'tickets', label: 'Ticket Debugging', icon: '🎯' },
  { id: 'streaks', label: 'Streaks & Daily', icon: '⚡' },
  { id: 'milestones', label: 'XP & Level Ranks', icon: '🌟' },
  { id: 'quality', label: 'Code Quality & Security', icon: '🛡️' },
];

export const RARITY_TIERS = {
  common: {
    label: 'Common',
    color: 'text-slate-400',
    bgColor: 'bg-slate-500/10',
    borderColor: 'border-slate-700/60',
    glowColor: 'hover:shadow-slate-500/20',
    badgeBg: 'bg-slate-800 text-slate-300 border-slate-700',
    icon: '🥉',
  },
  rare: {
    label: 'Rare',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/40',
    glowColor: 'hover:shadow-cyan-500/30',
    badgeBg: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
    icon: '🥈',
  },
  epic: {
    label: 'Epic',
    color: 'text-purple-400',
    bgColor: 'bg-purple-500/10',
    borderColor: 'border-purple-500/40',
    glowColor: 'hover:shadow-purple-500/40',
    badgeBg: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    icon: '🥇',
  },
  legendary: {
    label: 'Legendary',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/50',
    glowColor: 'hover:shadow-amber-500/50',
    badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/50',
    icon: '👑',
  },
  mythic: {
    label: 'Mythic',
    color: 'text-rose-400',
    bgColor: 'bg-rose-500/15',
    borderColor: 'border-rose-500/60',
    glowColor: 'hover:shadow-rose-500/60',
    badgeBg: 'bg-rose-500/25 text-rose-300 border-rose-500/60',
    icon: '🔥',
  },
};

export const BADGES_CATALOG = [
  // --- JOB SIMULATIONS ---
  {
    id: 'sim_first',
    title: 'First Simulation Solved',
    description: 'Successfully complete your first real-world job simulation codebase.',
    category: 'simulations',
    icon: '🚀',
    rarity: 'common',
    xpReward: 100,
    rarityPct: '88.4%',
    reqType: 'scenarios',
    reqVal: 1,
    requirementText: 'Complete 1 job simulation scenario',
  },
  {
    id: 'sim_5',
    title: '5 Job Simulations Solved',
    description: 'Finish 5 full-stack simulation codebases across different roles.',
    category: 'simulations',
    icon: '💼',
    rarity: 'rare',
    xpReward: 300,
    rarityPct: '42.1%',
    reqType: 'scenarios',
    reqVal: 5,
    requirementText: 'Complete 5 job simulation scenarios',
  },
  {
    id: 'sim_10',
    title: 'Simulation Veteran',
    description: 'Master 10 multi-ticket real production simulations.',
    category: 'simulations',
    icon: '🏢',
    rarity: 'epic',
    xpReward: 750,
    rarityPct: '18.5%',
    reqType: 'scenarios',
    reqVal: 10,
    requirementText: 'Complete 10 job simulation scenarios',
  },
  {
    id: 'sim_25',
    title: 'Staff Architect Engineer',
    description: 'Complete 25 enterprise-grade job simulations across all stacks.',
    category: 'simulations',
    icon: '👑',
    rarity: 'legendary',
    xpReward: 2000,
    rarityPct: '3.2%',
    reqType: 'scenarios',
    reqVal: 25,
    requirementText: 'Complete 25 job simulation scenarios',
  },
  {
    id: 'sim_junior',
    title: 'Junior Tier Graduate',
    description: 'Clear all Junior Level job simulations with passing scores.',
    category: 'simulations',
    icon: '🌱',
    rarity: 'common',
    xpReward: 150,
    rarityPct: '74.0%',
    reqType: 'tier',
    reqVal: 1,
    requirementText: 'Clear Junior tier simulations',
  },
  {
    id: 'sim_mid',
    title: 'Mid-Level Specialist',
    description: 'Clear all Mid-Level difficulty job simulations with high quality.',
    category: 'simulations',
    icon: '⚡',
    rarity: 'rare',
    xpReward: 400,
    rarityPct: '35.8%',
    reqType: 'tier',
    reqVal: 2,
    requirementText: 'Clear Mid-Level tier simulations',
  },
  {
    id: 'sim_senior',
    title: 'Senior Architect',
    description: 'Clear all Senior Level difficulty simulation scenarios.',
    category: 'simulations',
    icon: '🔥',
    rarity: 'epic',
    xpReward: 1000,
    rarityPct: '12.4%',
    reqType: 'tier',
    reqVal: 3,
    requirementText: 'Clear Senior tier simulations',
  },
  {
    id: 'sim_lead',
    title: 'Principal Lead Monarch',
    description: 'Clear all Lead Engineer difficulty job simulations.',
    category: 'simulations',
    icon: '💎',
    rarity: 'mythic',
    xpReward: 2500,
    rarityPct: '1.2%',
    reqType: 'tier',
    reqVal: 4,
    requirementText: 'Clear Lead Engineer tier simulations',
  },

  // --- STACK MASTERY ---
  {
    id: 'node_rookie',
    title: 'Node.js Novice',
    description: 'Complete 1 backend Node.js simulation scenario.',
    category: 'mastery',
    icon: '🟢',
    rarity: 'common',
    xpReward: 100,
    rarityPct: '68.0%',
    reqType: 'lang',
    reqVal: 'node',
    requirementText: 'Complete 1 Node.js simulation',
  },
  {
    id: 'node_pro',
    title: 'Node.js System Architect',
    description: 'Complete 5 complex Node.js microservice scenarios.',
    category: 'mastery',
    icon: '⚡',
    rarity: 'epic',
    xpReward: 600,
    rarityPct: '15.9%',
    reqType: 'lang',
    reqVal: 'node_5',
    requirementText: 'Complete 5 Node.js simulations',
  },
  {
    id: 'react_dev',
    title: 'React UI Specialist',
    description: 'Complete 1 frontend React simulation scenario.',
    category: 'mastery',
    icon: '⚛️',
    rarity: 'common',
    xpReward: 100,
    rarityPct: '72.3%',
    reqType: 'lang',
    reqVal: 'react',
    requirementText: 'Complete 1 React simulation',
  },
  {
    id: 'react_master',
    title: 'React State Wizard',
    description: 'Complete 5 complex React state management scenarios.',
    category: 'mastery',
    icon: '🔮',
    rarity: 'epic',
    xpReward: 600,
    rarityPct: '14.1%',
    reqType: 'lang',
    reqVal: 'react_5',
    requirementText: 'Complete 5 React simulations',
  },
  {
    id: 'python_dev',
    title: 'Pythonic AST Ninja',
    description: 'Complete 1 Python static analysis scenario.',
    category: 'mastery',
    icon: '🐍',
    rarity: 'rare',
    xpReward: 250,
    rarityPct: '31.0%',
    reqType: 'lang',
    reqVal: 'python',
    requirementText: 'Complete 1 Python simulation',
  },
  {
    id: 'mongo_dev',
    title: 'MongoDB Aggregation Master',
    description: 'Implement complex MongoDB database pipelines.',
    category: 'mastery',
    icon: '🍃',
    rarity: 'rare',
    xpReward: 250,
    rarityPct: '29.4%',
    reqType: 'lang',
    reqVal: 'mongo',
    requirementText: 'Complete 1 MongoDB simulation',
  },
  {
    id: 'docker_dev',
    title: 'Docker Containerizer',
    description: 'Execute isolated test suites inside Docker environments.',
    category: 'mastery',
    icon: '🐳',
    rarity: 'epic',
    xpReward: 500,
    rarityPct: '19.8%',
    reqType: 'docker',
    reqVal: 5,
    requirementText: 'Execute sandboxed Docker runs 5 times',
  },
  {
    id: 'fullstack_monarch',
    title: 'Full Stack Shadow Monarch',
    description: 'Master fullstack React + Node + Mongo end-to-end architectures.',
    category: 'mastery',
    icon: '🌌',
    rarity: 'mythic',
    xpReward: 2500,
    rarityPct: '0.9%',
    reqType: 'fullstack_all',
    reqVal: 1,
    requirementText: 'Complete fullstack master scenarios',
  },

  // --- TICKET DEBUGGING ---
  {
    id: 'ticket_1',
    title: 'First Jira Ticket Closed',
    description: 'Resolve your first Jira ticket in a simulation workspace.',
    category: 'tickets',
    icon: '🎟️',
    rarity: 'common',
    xpReward: 50,
    rarityPct: '91.2%',
    reqType: 'tickets',
    reqVal: 1,
    requirementText: 'Resolve 1 Jira ticket',
  },
  {
    id: 'ticket_10',
    title: '10 Jira Tickets Closed',
    description: 'Resolve 10 production Jira tickets successfully.',
    category: 'tickets',
    icon: '🎫',
    rarity: 'rare',
    xpReward: 250,
    rarityPct: '48.0%',
    reqType: 'tickets',
    reqVal: 10,
    requirementText: 'Resolve 10 Jira tickets',
  },
  {
    id: 'ticket_50',
    title: '50 Jira Tickets Closed',
    description: 'Resolve 50 production Jira tickets across codebases.',
    category: 'tickets',
    icon: '🏅',
    rarity: 'epic',
    xpReward: 750,
    rarityPct: '11.3%',
    reqType: 'tickets',
    reqVal: 50,
    requirementText: 'Resolve 50 Jira tickets',
  },
  {
    id: 'ticket_100',
    title: '100 Jira Tickets Closed',
    description: 'Resolve 100 Jira tickets! Master ticket solver of DevTier.',
    category: 'tickets',
    icon: '🏆',
    rarity: 'legendary',
    xpReward: 1500,
    rarityPct: '2.8%',
    reqType: 'tickets',
    reqVal: 100,
    requirementText: 'Resolve 100 Jira tickets',
  },
  {
    id: 'bug_hunter',
    title: 'Critical Bug Hunter',
    description: 'Fix 10 critical vulnerability bug tickets.',
    category: 'tickets',
    icon: '🐛',
    rarity: 'rare',
    xpReward: 300,
    rarityPct: '33.5%',
    reqType: 'bug_type',
    reqVal: 10,
    requirementText: 'Fix 10 critical bug tickets',
  },
  {
    id: 'refactor_pro',
    title: 'Refactoring Guru',
    description: 'Complete 10 refactoring tickets with zero syntax regressions.',
    category: 'tickets',
    icon: '♻️',
    rarity: 'epic',
    xpReward: 500,
    rarityPct: '16.7%',
    reqType: 'refactor_type',
    reqVal: 10,
    requirementText: 'Complete 10 refactor tickets',
  },

  // --- STREAKS & CONSISTENCY ---
  {
    id: 'streak_3',
    title: '3-Day Active Streak',
    description: 'Maintain a 3-day continuous daily coding streak.',
    category: 'streaks',
    icon: '🔥',
    rarity: 'common',
    xpReward: 100,
    rarityPct: '62.5%',
    reqType: 'streak',
    reqVal: 3,
    requirementText: 'Maintain 3-day active streak',
  },
  {
    id: 'streak_7',
    title: '7-Day Unstoppable Streak',
    description: 'Maintain a 7-day continuous daily coding streak.',
    category: 'streaks',
    icon: '⚡',
    rarity: 'rare',
    xpReward: 350,
    rarityPct: '28.9%',
    reqType: 'streak',
    reqVal: 7,
    requirementText: 'Maintain 7-day active streak',
  },
  {
    id: 'streak_30',
    title: '30-Day Legend Streak',
    description: 'Maintain a 30-day continuous daily coding streak!',
    category: 'streaks',
    icon: '🌟',
    rarity: 'legendary',
    xpReward: 1500,
    rarityPct: '4.1%',
    reqType: 'streak',
    reqVal: 30,
    requirementText: 'Maintain 30-day active streak',
  },
  {
    id: 'streak_100',
    title: '100-Day Immutable Streak',
    description: 'Maintain an epic 100-day daily coding streak!',
    category: 'streaks',
    icon: '💫',
    rarity: 'mythic',
    xpReward: 3000,
    rarityPct: '0.4%',
    reqType: 'streak',
    reqVal: 100,
    requirementText: 'Maintain 100-day active streak',
  },

  // --- XP & LEVEL MILESTONES ---
  {
    id: 'lvl_5',
    title: 'Level 5 Achieved',
    description: 'Reach Developer Level 5.',
    category: 'milestones',
    icon: '⭐',
    rarity: 'common',
    xpReward: 100,
    rarityPct: '79.2%',
    reqType: 'level',
    reqVal: 5,
    requirementText: 'Reach Level 5',
  },
  {
    id: 'lvl_10',
    title: 'Level 10 Achieved',
    description: 'Reach Developer Level 10.',
    category: 'milestones',
    icon: '🌟',
    rarity: 'rare',
    xpReward: 250,
    rarityPct: '45.1%',
    reqType: 'level',
    reqVal: 10,
    requirementText: 'Reach Level 10',
  },
  {
    id: 'lvl_25',
    title: 'Level 25 Achieved',
    description: 'Reach Developer Level 25.',
    category: 'milestones',
    icon: '✨',
    rarity: 'epic',
    xpReward: 600,
    rarityPct: '17.3%',
    reqType: 'level',
    reqVal: 25,
    requirementText: 'Reach Level 25',
  },
  {
    id: 'lvl_50',
    title: 'Level 50 Grandmaster',
    description: 'Reach Developer Level 50!',
    category: 'milestones',
    icon: '⚜️',
    rarity: 'legendary',
    xpReward: 1500,
    rarityPct: '2.5%',
    reqType: 'level',
    reqVal: 50,
    requirementText: 'Reach Level 50',
  },
  {
    id: 'xp_1000',
    title: '1,000 XP Club',
    description: 'Accumulate 1,000 total Experience Points.',
    category: 'milestones',
    icon: '💎',
    rarity: 'common',
    xpReward: 150,
    rarityPct: '65.4%',
    reqType: 'xp',
    reqVal: 1000,
    requirementText: 'Accumulate 1,000 XP',
  },
  {
    id: 'xp_5000',
    title: '5,000 XP Elite',
    description: 'Accumulate 5,000 total Experience Points.',
    category: 'milestones',
    icon: '🌌',
    rarity: 'rare',
    xpReward: 500,
    rarityPct: '24.1%',
    reqType: 'xp',
    reqVal: 5000,
    requirementText: 'Accumulate 5,000 XP',
  },
  {
    id: 'xp_10000',
    title: '10,000 XP Shadow Monarch',
    description: 'Accumulate 10,000 total Experience Points!',
    category: 'milestones',
    icon: '🔮',
    rarity: 'legendary',
    xpReward: 2000,
    rarityPct: '1.9%',
    reqType: 'xp',
    reqVal: 10000,
    requirementText: 'Accumulate 10,000 XP',
  },

  // --- CODE QUALITY & SECURITY ---
  {
    id: 'ast_100',
    title: '100% AST Quality Score',
    description: 'Achieve a perfect 100/100 AST score on code analysis.',
    category: 'quality',
    icon: '🛡️',
    rarity: 'epic',
    xpReward: 500,
    rarityPct: '13.8%',
    reqType: 'ast',
    reqVal: 100,
    requirementText: 'Achieve 100/100 AST score',
  },
  {
    id: 'rce_shield',
    title: 'Docker Security Shield',
    description: 'Execute isolated code evaluation with zero safety warnings.',
    category: 'quality',
    icon: '🔒',
    rarity: 'rare',
    xpReward: 300,
    rarityPct: '37.4%',
    reqType: 'security',
    reqVal: 1,
    requirementText: 'Execute secure Docker evaluation',
  },
  {
    id: 'clean_code',
    title: 'Clean Code Guardian',
    description: 'Pass 5 code reviews with zero anti-patterns or code smells.',
    category: 'quality',
    icon: '✨',
    rarity: 'epic',
    xpReward: 600,
    rarityPct: '10.5%',
    reqType: 'clean',
    reqVal: 5,
    requirementText: 'Pass 5 reviews with 0 code smells',
  },
];
